import type { Skill } from "./agents.js";

/**
 * What a standalone executable carries in place of the files beside the npm
 * package: it has no package.json and no dist/skills/ next to it. The
 * executable's entry, generated by scripts/build-executable.mjs, calls
 * `embed` before it loads the CLI.
 */
export interface Embedded {
  version: string;
  skills: Skill[];
}

let embedded: Embedded | undefined;

export function embed(content: Embedded): void {
  embedded = content;
}

export function embeddedContent(): Embedded | undefined {
  return embedded;
}
